version: 0.2

phases:
  install:
    commands:
      - echo "Checking Python and pip..."
      - python --version
      - pip --version
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
  build:
    commands:
      - echo "Running Django tests..."
      - python manage.py test
  post_build:
    commands:
      - echo "Test completed"
