version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "eu-north-1"
    AWS_ACCOUNT_ID: "472400096032"
    ECR_REPO_NAME: "aws-demo/backend"
    ECR_IMAGE_TAG: "latest"

phases:
  install:
    commands:
      - echo "Checking Python and pip..."
      - python --version
      - pip --version
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
  build:
    commands:
      - echo "Running Django tests..."
      - python manage.py test
  post_build:
    commands:
      - echo "Build and test completed successfully!"
